#Day 1 of ML CODE - Data PreProcessing. 

> Feature Encoding. 

> Missing Data Handling

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Avik-Jain/100-Days-Of-ML-Code/master/datasets/Data.csv')

In [ ]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
imputer = imputer.fit(X.iloc[:,1:])

imputed_data = imputer.transform(X.iloc[:,1:])

In [ ]:
X.iloc[:,1:] = imputed_data

In [ ]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [ ]:
#Encoding Categorical Data

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
labeler = LabelEncoder()

labelled_X = labeler.fit_transform(X.iloc[:,0])  

In [ ]:
labelled_X

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [ ]:
labeler.inverse_transform(labelled_X)

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [ ]:
# ohe = OneHotEncoder()

# ohe_labelled = ohe.fit_transform(X[['Country']].values)

In [ ]:
#

In [ ]:
# onehotencoder = OneHotEncoder(categorical_features = [0])
# # X = onehotencoder.fit_transform(X).toarray()
# # labelencoder_Y = LabelEncoder()
# # Y =  labelencoder_Y.fit_transform(Y)

In [ ]:
drop_enc = OneHotEncoder(drop='first').fit(X.iloc[:,[0]])
drop_enc.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [ ]:
ohe_labelled = drop_enc.transform(X.iloc[:,[0]]).toarray()

In [ ]:
ohe_labelled

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.]])

In [ ]:
# c = ['a','b','a','c','a','b']

In [ ]:
# ohe = OneHotEncoder()

In [ ]:
# ohe_fit = ohe.fit([c])

In [ ]:
# ohe_transformed = ohe.transform([c]).toarray()

In [ ]:
# ohe_transformed

# Complete Encoding Example

In [12]:
df = pd.DataFrame({'Fruits':['Apple','Banana','Orange','Apple','Banana','Banana','Orange']})

In [13]:
df

Fruits
0   Apple
1  Banana
2  Orange
3   Apple
4  Banana
5  Banana
6  Orange

In [14]:
#First Label Encoding. 
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
labelencoded = le.fit_transform(df.iloc[:,0])

In [17]:
labelencoded

array([0, 1, 2, 0, 1, 1, 2])

In [18]:
df['Fruits'] = labelencoded

In [19]:
df

Fruits
0       0
1       1
2       2
3       0
4       1
5       1
6       2

In [20]:
#Now onehot encoding. 

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [22]:
ohe = OneHotEncoder()

In [23]:
ohe_encoded = ohe.fit_transform(df).toarray()

In [26]:
df = pd.concat([df,pd.DataFrame(ohe_encoded)],axis=1)

In [27]:
df

Fruits    0    1    2
0       0  1.0  0.0  0.0
1       1  0.0  1.0  0.0
2       2  0.0  0.0  1.0
3       0  1.0  0.0  0.0
4       1  0.0  1.0  0.0
5       1  0.0  1.0  0.0
6       2  0.0  0.0  1.0

In [31]:
# ohe_encoded1 = np.array(ColumnTransformer.fit_transform()